[package]
name = "tipp10w"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
rusqlite = "0.32.1"

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
